const fs = require('fs');
const yaml = require('js-yaml');

/**
 * Generate comprehensive statistics and GitHub-ready markdown
 */
function generateStats(groups, totalSites, successfulResults) {
    const stats = {
        totalSites,
        successfulExtractions: successfulResults,
        failedExtractions: totalSites - successfulResults,
        successRate: ((successfulResults / totalSites) * 100).toFixed(2),
        totalGroups: groups.length,
        duplicateGroups: groups.filter(g => g.length > 1).length,
        uniqueLogos: groups.filter(g => g.length === 1).length,
        largestGroup: Math.max(...groups.map(g => g.length)),
        averageGroupSize: (groups.reduce((sum, g) => sum + g.length, 0) / groups.length).toFixed(2),
        totalDuplicates: groups.reduce((sum, g) => g.length > 1 ? sum + (g.length - 1) : sum, 0)
    };

    // Group size distribution
    const sizeDistribution = {};
    groups.forEach(g => {
        const size = g.length;
        sizeDistribution[size] = (sizeDistribution[size] || 0) + 1;
    });

    // Top 10 largest groups
    const topGroups = groups
        .filter(g => g.length > 1)
        .sort((a, b) => b.length - a.length)
        .slice(0, 10);

    return { stats, sizeDistribution, topGroups };
}

/**
 * Create ASCII bar chart
 */
function createBarChart(data, maxWidth = 50) {
    const entries = Object.entries(data).sort((a, b) => parseInt(a[0]) - parseInt(b[0]));
    const maxValue = Math.max(...entries.map(e => e[1]));
    
    let chart = '';
    entries.forEach(([key, value]) => {
        const barLength = Math.ceil((value / maxValue) * maxWidth);
        const bar = '█'.repeat(barLength);
        chart += `${key.padStart(3)} sites │${bar} ${value}\n`;
    });
    
    return chart;
}

/**
 * Generate GitHub-ready markdown report
 */
function generateMarkdown(analysisResults) {
    const { stats, sizeDistribution, topGroups } = analysisResults;
    
    const markdown = `# 📊 Logo Grouping Statistics

## 🎯 Overview

| Metric | Value |
|--------|-------|
| **Total Sites Processed** | ${stats.totalSites.toLocaleString()} |
| **Successful Logo Extractions** | ${stats.successfulExtractions.toLocaleString()} |
| **Failed Extractions** | ${stats.failedExtractions.toLocaleString()} |
| **Success Rate** | ${stats.successRate}% |
| **Total Groups Found** | ${stats.totalGroups.toLocaleString()} |
| **Groups with Duplicates** | ${stats.duplicateGroups.toLocaleString()} |
| **Unique Logos** | ${stats.uniqueLogos.toLocaleString()} |
| **Total Duplicate Instances** | ${stats.totalDuplicates.toLocaleString()} |

## 📈 Group Size Distribution

\`\`\`
${createBarChart(sizeDistribution)}
\`\`\`

## 🏆 Top 10 Largest Duplicate Groups

${topGroups.map((group, idx) => `### ${idx + 1}. Group with ${group.length} sites

<details>
<summary>Click to expand sites</summary>

${group.map(item => `- ${item.site}`).join('\n')}

**Sample Logo:** ${group[0].logoUrl}

</details>
`).join('\n')}

## 💡 Key Insights

- **Duplicate Detection Rate:** ${((stats.duplicateGroups / stats.totalGroups) * 100).toFixed(2)}% of groups contain duplicates
- **Average Group Size:** ${stats.averageGroupSize} sites per group
- **Largest Group:** ${stats.largestGroup} identical logos found
- **Efficiency:** Found ${stats.totalDuplicates} duplicate logo instances across ${stats.duplicateGroups} groups

---

*Generated by Logo Grouping Engine • ${new Date().toLocaleString()}*
`;

    return markdown;
}

/**
 * Main function to generate and save statistics
 */
function generateAndSaveStats(groups, totalSites) {
    const successfulResults = groups.reduce((sum, g) => sum + g.length, 0);
    
    console.log('\n📊 Generating statistics...');
    
    const analysisResults = generateStats(groups, totalSites, successfulResults);
    const markdown = generateMarkdown(analysisResults);
    
    // Save markdown file
    fs.writeFileSync('STATS.md', markdown, 'utf8');
    console.log('✅ Statistics saved to STATS.md');
    
    // Also save JSON for programmatic access
    const jsonStats = {
        generated: new Date().toISOString(),
        ...analysisResults.stats,
        sizeDistribution: analysisResults.sizeDistribution,
        topGroups: analysisResults.topGroups.map(g => ({
            size: g.length,
            sites: g.map(item => item.site)
        }))
    };
    
    fs.writeFileSync('stats.json', JSON.stringify(jsonStats, null, 2), 'utf8');
    console.log('✅ JSON statistics saved to stats.json');
    
    // Print summary to console
    console.log('\n' + '='.repeat(60));
    console.log('📊 STATISTICS SUMMARY');
    console.log('='.repeat(60));
    console.log(`Total Sites:        ${analysisResults.stats.totalSites.toLocaleString()}`);
    console.log(`Success Rate:       ${analysisResults.stats.successRate}%`);
    console.log(`Total Groups:       ${analysisResults.stats.totalGroups.toLocaleString()}`);
    console.log(`Duplicate Groups:   ${analysisResults.stats.duplicateGroups.toLocaleString()}`);
    console.log(`Largest Group:      ${analysisResults.stats.largestGroup} sites`);
    console.log('='.repeat(60));
    
    return analysisResults;
}

module.exports = { generateAndSaveStats };